version: '3.8'

services:
  nginx:
    build: ./requirement/nginx
    ports:
      - "443:443"
    container_name: nginx
    image: nginx:42
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    restart: always
  mariadb:
    image: mariadb:42
    build: ./requirement/mariaDB
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: always
  wordpress:
    image: wordpress:42
    build: ./requirement/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/html
  redis:
    image: redis:42
    container_name: redis
    build: ./requirement/bonus/redis
    volumes:
     - wordpress_v:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  adminer:
    image: adminer:42
    container_name: adminer
    build: ./requirement/bonus/adminer
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: always
  web:
    image: web:42
    container_name: web
    build: ./requirement/bonus/website
    networks:
      - inception
    ports:
      - "5555:5555"
    restart: always
  cadvisor:
    image: cadvisor:42
    container_name: cadvisor
    build: ./requirement/bonus/cadvisor
    networks:
      - inception
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: always
  ftp:
    image: ftp:42
    container_name: ftp
    env_file:
      - .env
    build: ./requirement/bonus/ftp
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - wordpress_v:/home/aboukdid/ftp
    restart: always


networks:
  inception:
    driver: bridge

volumes:
  mariadb_v:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/aboukdid/data/mariadb
      o: bind
      type: none
  wordpress_v:
    name: wordpress
    driver: local
    driver_opts: 
      device: /home/aboukdid/data/wordpress
      o: bind
      type: none
