version: '3.8'

services:
  nginx:
    build: ./requirement/Nginx
    ports:
      - "443:443"
    container_name: Nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress_v:/var/www/html
    restart: always
  mariadb:
    build: ./requirement/MariaDB
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb_v:/var/lib/mysql
    restart: always
  wordpress:
    build: ./requirement/Wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_v:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb_v:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/aboubakr/data/mariadb
      o: bind
      type: none
  wordpress_v:
    name: wordpress
    driver: local
    driver_opts: 
      device: /home/aboubakr/data/wordpress
      o: bind
      type: none