#sudo vim /etc/hosts
version: '3.8'
services:
  nginx:
    build: ./requirement/Nginx
    ports:
      - "443:443"
    container_name: Nginx
    networks:
      - inception
    restart: always
  mariadb:
    build: ./requirement/MariaDB
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirement/Wordpress
    container_name: wordpress
    depends_on:
      - nginx
      - mariadb
    env_file:
      - .env
    restart: always
    ports:
      - "9000:9000"
    networks:
      - inception
networks:
  inception:
    driver: bridge


  